version: '3.8'
services:
  jira-addon-db:
    env_file: ./.env
    image: 'postgres:15'
    container_name: jira-addon-db
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  jira-addon-api:
    env_file: ./.env
    container_name: jira-addon-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - jira-addon-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jira-addon-db:${DB_PORT}/${POSTGRES_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SERVER_PORT=${APP_PORT}


  ngrok-server:
    env_file: ./.env
    container_name: jira-addon-ngrok-server
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--authtoken"
      - ${NGROK_AUTH_TOKEN}
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - "4040:4040"